# generated by datamodel-codegen:
#   filename:  meta_config.schema.yaml
#   timestamp: 2025-11-29T10:09:07+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Person(BaseModel):
    name: str
    email: Optional[str] = None


class MetaConfig(BaseModel):
    maintainers: Optional[List[Person]] = None
    authors: Optional[List[Person]] = None
    license: Optional[str] = None
    cmake_version: Optional[str] = None
    rust_edition: Optional[str] = None
    pkg_default_version: Optional[str] = None
    workspace_path: Optional[str] = None
    assets_path: Optional[str] = None
    data_path: Optional[str] = None
