# generated by datamodel-codegen:
#   filename:  universe.schema.yaml
#   timestamp: 2025-11-29T10:09:04+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel


class Type(Enum):
    interface = 'interface'
    node = 'node'
    algorithm = 'algorithm'
    launch = 'launch'


class Lang(Enum):
    cpp = 'cpp'
    rust = 'rust'


class Repo(BaseModel):
    repo: str
    url: Optional[str] = None
    version: Optional[str] = None
    subpaths: Optional[List[str]] = []


class Person(BaseModel):
    name: str
    email: str


class Param(BaseModel):
    param: str
    type: Optional[str] = None
    unit: Optional[str] = None
    description: Optional[str] = None
    default: Optional[Union[str, float, bool, int]] = None


class InterfaceType(Enum):
    msg = 'msg'
    srv = 'srv'
    action = 'action'


class IoType(Enum):
    input = 'input'
    output = 'output'


class Interface(BaseModel):
    msg: Optional[str] = None
    srv: Optional[str] = None
    action: Optional[str] = None
    name: Optional[str] = None
    type: str
    interface_type: Optional[InterfaceType] = None
    io_type: Optional[IoType] = None
    namespace: Optional[str] = None
    remapping: Optional[str] = None
    description: Optional[str] = None
    dependency: Optional[str] = None


class Field(BaseModel):
    name: str
    type: Optional[str] = None
    description: Optional[str] = None
    dependency: Optional[str] = None


class Msg(BaseModel):
    msg: str
    fields: Optional[List[Field]] = []
    description: Optional[str] = None
    dependencies: Optional[str] = None
    references: Optional[List[str]] = []


class Srv(BaseModel):
    srv: str
    requests: Optional[List[Field]] = []
    responses: Optional[List[Field]] = []
    description: Optional[str] = None
    dependencies: Optional[List[str]] = []
    references: Optional[List[str]] = []


class Action(BaseModel):
    action: str
    goal_requests: Optional[List[Field]] = []
    responses: Optional[List[Field]] = []
    feedbacks: Optional[List[Field]] = []
    description: Optional[str] = None
    dependencies: Optional[List[str]] = []
    references: Optional[List[str]] = []


class Pkg(BaseModel):
    pkg: str
    type: Optional[Type] = None
    lang: Optional[Lang] = None
    source_codes: Optional[List[str]] = []
    dependencies: Optional[List[str]] = []
    build_depends: Optional[List[str]] = []
    exec_depends: Optional[List[str]] = []
    test_depends: Optional[List[str]] = []
    description: Optional[str] = None
    msgs: Optional[List[Msg]] = []
    srvs: Optional[List[Srv]] = []
    actions: Optional[List[Action]] = []
    purpose: Optional[str] = None
    design: Optional[str] = None
    inputs: Optional[List[Interface]] = []
    outputs: Optional[List[Interface]] = []
    parameters: Optional[List[Param]] = []
    references: Optional[List[str]] = []
    cmake_version: Optional[str] = None
    install_to_share: Optional[List[str]] = []
    rust_edition: Optional[str] = None
    version: Optional[str] = None
    maintainers: Optional[List[Person]] = []
    authors: Optional[List[Person]] = []
    license: Optional[str] = None


class Module(BaseModel):
    module: str
    children: Optional[List[Union[Module, Pkg, Repo]]] = []


class Universe(BaseModel):
    universe: Optional[List[Union[Module, Pkg, Repo]]] = None


Module.update_forward_refs()
